### ISSUE TITLE
Questions regarding the paper 

### ISSUE THREAD

**Issue by KhanhNgoDuy** [ymhe12/GS-Phong#1]
Hi, I have a few questions about the paper.
1. Is the Blinn-Phong model more suitable for representing the shadow than the other models?
2. In algorithm 1, you mentioned about the shadow coefficient `phi`. What is this coefficient called in other equations, since I cannot find `phi` in the rest of the paper.

Thank you in advance, I really appreciate your answer.

![image](https://github.com/user-attachments/assets/8b55d4ee-63d1-4236-87ba-66adf7ff50d8)

**Comment by rainy2323** [comment]
Hi, thank you for your interest in our work!
> Is the Blinn-Phong model more suitable for representing the shadow than the other models?

In this aspect, they are essentially the same. Both the Blinn-Phong model and other models, like the rendering function, require occlusion information (for example, the occlusion term in GS-IR) for training. This occlusion term is trained alongside the parameters of the lighting model. We chose the Blinn-Phong model for its simplicity and explicitness, which enhances its generalization ability, especially in out-of-distribution (OOD) scenarios.

> In algorithm 1, you mentioned about the shadow coefficient phi. What is this coefficient called in other equations, since I cannot find phi in the rest of the paper.

Sorry for the confusion. The shadow coefficient $\phi$ is a factor applied to the light intensity $T_i^\text{light}$.

Similar to the idea of camera-to-point accumulated transmittance in 3DGS, our light intensity defines the accumulated transmittance of light intensity along the light-to-point ray, thus is influenced by the magnitude of the opacities. To facilitate learning and convergence, we added a coefficient $\phi$ to this term, referred to as the shadow coefficient. Thus the shadow computing equation (Eq.4) should be updated as:

$$
L_p = k_aI_a + \phi T_i^\text{light} \times \sum\limits_{m \in \text{lights}} (k_dI_d + k_sI_s).
$$

Let me know if you have other questions.

**Comment by KhanhNgoDuy** [comment]
Thank you for your response. If this is the case, then the shadow coefficient will be a global term, instead of being an attribute of the Gaussian right?

**Comment by rainy2323** [comment]
Yes, the shadow coefficient is a global parameter

**Comment by KhanhNgoDuy** [comment]
Hi, I have another question about the Eq. 4 and 5 in the paper. 

How to obtain $I$ and $I_a$ in these equations? Are they provided in the dataset, or calculated with any formula?
```math 
L_p = L_a + L_d + L_s = k_a I_a + \sum{ \left( k_d I_d + k_s I_s \right) } \left(4\right)
```
```math
I_d = \frac{I}{r^2} \text{max}\left(0, n \cdot l \right), 
I_s = \frac{I}{r^2} \text{max}\left(0, n \cdot h \right)^p \left(5\right)
```

Sorry if my question is obvious, since I am very new to this field.
